title: Ship It Immediately
email: duncan.grubbs@gmail.com
description: >-
  Thoughts on software "engineering"
baseurl: ""
url: "https://duncangrubbs.com"
github_username: duncangrubbs

theme: minima
plugins:
  - jekyll-feed
